### ISSUE TITLE
Polish translation of the randomizer

### ISSUE THREAD

**Issue by Gusti23** [on3iro/aer-data#2]
Hi on3iro,

I could provide polish language data for the app. We have the same situation as in France - we have translated 1st wave of Aeon's End and 2nd wave. Legacy version will be later this year. I have plenty of free time to translate all the cards, but I really don't have much experience in programming. You would need to guide me through the process translation.

Thanks,
Simon

**Comment by on3iro** [comment]
Hi @Gusti23 sure thing :)

I will gladely guide you along the way :)
Actually it won't be too hard - the files themselves aren't really programming, but rather some data with a certain structure. However there are a few tiny bits of html involved.
Would it be possible for you to do a bit of pair programming via discord or jitsi?

That way I could simply show you the basics you need to know and you could immediately ask questions.

**Comment by Gusti23** [comment]
Yes, I could connect via discord. But here is a thing - I am not a developer. I didn't write a single line of code in my entire life. If you walk me through I could copy your steps.

**Comment by on3iro** [comment]
@Gusti23 no worries - as I mentioned before, this isn't really programming. You can get pretty far by pattern matching.

One thing you could do in preparation, is to install [git](https://git-scm.com/). This is a very popular version control system, which is also used by github. This allows you to create your content and incrementally build on it (versions or commits). Furthermore I can then review the code you produced.
It's enough for if you just install it, i'll show you the necessary basics later on. This will probably be  the most complicated part for you.
Another thing you need is a good text editor.
I recommend [vs code](https://code.visualstudio.com/).

If you have all this in place, we can do a pair programming session during the upcoming week (somewhere in the evening).

**Comment by Gusti23** [comment]
I fulfilled all the initial requirements in particular downloading and installing git and vs code. Someone help me to clone this repository as well. That person can also help me with further steps, so please describe them and we should be able to complete them ourselves.

**Comment by on3iro** [comment]
Cool - I'll write down a few instructions asap :)

**Comment by on3iro** [comment]
@Gusti23 ok, I think you can start now. @jannydiamond was so kind to provide the instructions inside the [README](https://github.com/on3iro/aer-data/blob/master/README.md).

Let me know if anything is unclear or you have further questions

**Comment by Gusti23** [comment]
Everything is ready. Only one spell in Promos cards was translate into polish and only one nemesis card wasn't translate. We also don't have treasures promo cards yet.
